ReDI-School/F24-Berlin-Web-Circle

README.md
Added my name, Bohdan Hrabynskyi, to the Collaborators section in the README. Closes #8.
=> Added Bohdan Hrabynskyi to Collaborators section

README.md
Closes #18 
Please review my changes, and approve if okay.
=> Added my name, Michael Kleinschmidt, to the README

README.md
added the name konzi to collaborators on read me file #17
=> Added my name to list of collaborators

README.md
Contributors name  and handles added to README file for Kalina Iwaszko
=> Kalina Iwaszko added to Contributors in README

src/App.jsx
Added Product Page Links to the Home Page as an example.
Since product details are not yet finalized a dummy array of places are used.
=> Add a Product Link to the Home page

src/components/Footer/Footer.jsx, src/components/Footer/Footer.module.css, src/pages/Root.jsx, src/theme/colors.js
Replaced the dummy footer component with the copywrite message.
I included a colors.js file inside the theme folder where I defined the colors I used for footer top border and text.
=> Add the basic Footer

src/components/ReservationCard/ReservationCard.jsx, src/components/ReservationCard/ReservationCard.module.css, src/pages/ProductPage.jsx
Reservation card component includes: 
1. Reservation section:
- Price per night
- Check in/out dates
- Guest number
- Reserve button
2. Cost summary component
Reservation card component is imported inside product page.
=> Add feature/stay date and people picker

src/components/ProductHighlight/ProductHighlight.jsx, src/components/ProductHighlight/ProductHighlight.module.css, src/constants/constants.js, src/icons/CalendarIcon.jsx, src/icons/DoorIcon.jsx, src/icons/MedalIcon.jsx, src/icons/PinIcon.jsx, src/icons/index.js, src/pages/ProductPage.jsx
Add Product Highlights to the product Page.
Icons are added to a separate file considering the possibility of reuse.
View after implementation:
=> Feature add product highlights

src/components/AddGuestsPopUp/AddGuestsPopUp.module.css, src/components/AddGuestsPopUp/Guest/Guest.jsx, src/components/AddGuestsPopUp/Guest/Guest.module.css
=> Bug fix for padding issue and hover issue

src/components/AboveProductTitle/AboveProductTitle.jsx, src/components/AboveProductTitle/AboveProductTitle.module.css, src/pages/ProductPage.jsx
I have added a title at the top of the product gallery.
=> Adding a title for the product page

src/components/FavoriteStay/FavoriteStay.jsx, src/components/ReservationCard/ReservationCard.module.css
=> Fixed heights for favourite stay and reservation card components. 

src/pages/ProductPage.module.css
The position of the Reservation Card is now sticky and moves vertically as you scroll.
=> sticky reservation card

package-lock.json, package.json, server/index.js, server/package-lock.json, server/package.json, src/App.jsx
To review this ticket, please first go to the "server" folder and install npm. In addition, install npm for frontend, as I installed the axios package. Also, you should run both the front and backend, which means opening two terminals. One for the frontend and another for the backend (server).
front: npm run dev
server: npm start
In the end, this message should appear on the main page: "This is from backend!"
=> adding backend to the project

src/components/LanguagePopUp/LanguagePopUp.jsx, src/components/LanguagePopUp/LanguagePopUp.module.css, src/components/LanguageSelector/LanguageSelector.jsx, src/components/LanguageSelector/LanguageSelector.module.css, src/components/ModalPopUp/ModalPopUp.jsx, src/components/ModalPopUp/ModalPopUp.module.css, src/icons/CloseIcon.jsx, src/icons/index.js
[#83](https://github.com/ReDI-School/F24-Berlin-Web-Circle/issues/83)
=> Create common Modal PopUp

server/index.js, server/routes/destinations.js, server/routes/places.js, server/src/data/destinations.json
refactored the folder structure allitle bit , added a dummy destinations.json for use to filter the destinations.
created autocomplete/filter route.
=> add autocomplete in destinations endpoint and refactor the server files

src/pages/ProductPage.jsx
removed unncessary code in product page.
=> fixing product-page

src/components/Amenities/Amenities.jsx, src/components/Amenities/Amenities.module.css
=> Refactor amenities section to make it dynamic

src/index.css
I removed the dark mode in index.css
=> Removing the dark mode

src/components/Header/Header.jsx
=> Removed destination and guests popup from header

server/src/data/places.json
I added 30 places with all images to the places.json
=> More products and images in places.json

src/pages/ProductPage.jsx
the reviews summary now receives dynamic values
=> make review summary dynamic

src/pages/ProductPage.module.css
now the tite page is visible as before
=> fix the title in product page to be visible

src/components/Calendar/Calendar.module.css, src/components/CategoryTabs/CategoryTabs.module.css, src/components/Header/Header.module.css, src/components/ReservationCard/PopUp/PopUp.module.css, src/components/SearchBar/SearchBar.module.css
All issues with overlapping elements have been resolved: Now it looks like this:
=> Fix issues with z-indexes and overlapping

src/App.jsx, src/components/CategoryTabs/CategoryTabs.jsx, src/components/CategoryTabs/CategoryTabs.module.css, src/components/FilterButton/FilterButton.jsx, src/components/FilterButton/FilterButton.module.css
I added a FilterButton Component. Please approve it!
=> FilterButton added

server/prisma/migrations/20241119170946_web_circle/migration.sql, server/prisma/migrations/20241121162738_web_circle/migration.sql, server/prisma/schema.prisma
In this ticket, I added the models for the tables to the schema.prisma. After running npx prisma generate, which generates the Prisma client, and npx prisma migrate dev to apply the migrations, you should be able to see the tables in the database.
=> Adding models to the schema.prisma

package-lock.json, package.json, server/package.json, src/components/CategoryTabs/CategoryTabs.jsx, src/components/CategoryTabs/CategoryTabs.module.css
Made CtegoryTab Responsive.
Added Touch Scrolling Support for CategoryTabs (mobile version):
Implemented onTouchStart and onTouchMove to enable smooth horizontal scrolling for touch devices.
Captures initial touch position (touchStartX) on onTouchStart.
Calculates swipe distance and scrolls the container smoothly using scrollBy in onTouchMove.
Ensures intuitive and responsive touch interactions, particularly for mobile and tablet users.
Existing functionality for arrow buttons and desktop scroll remains unaffected.
=> categoryTab-responsive

src/components/SearchPanel/SearchPanel.jsx
This PR resolves a bug in the handleAirbnbSearch function by improving parameter handling. The issue was addressed by replacing the guests parameter with separate parameters for adults, children, infants, and pets.
=> Fix bug with paraments in handleAirbnbSearch function

package-lock.json, src/components/Calendar/Calendar.test.jsx
This PR adds a test for the Calendar component to ensure that the setCheckInDate and setCheckOutDate functions are called once on the initial load when no dates are set.
=> Create tests for Calendar component

src/components/ProductHighlight/ProductHighlight.jsx, src/components/ProductHighlight/ProductHighlight.test.jsx, src/components/SearchPanel/SearchPanel.jsx
After adding '@testing-library/jest-dom'  to the test, the tests works as expected. I deleted also unneccesary arguments since we don't use them in the SearchBar.
=> Add missing dependencies to the test

src/App.css, src/components/Header/Header.module.css, src/components/HeaderUserMenu/HeaderUserMenu.module.css, src/components/LanguageSelector/LanguageSelector.module.css
In this PR grid layout in the Home page was fixed by adding additional margin-bottom that prevent to hide product text under the footer. Additionaly the buttons in the right side of the Header was propperly aligned.
=> Fix grid layout and align button in the Header

src/components/HeaderUserMenu/HeaderUserMenu.module.css, src/components/ProductCard/ProductCard.jsx
This PR fix issue in the ProductCard by adding import for Link that was not added by mistake while resolving merge conflicts. Also here the shadow was changed  in the HeaderUserMenu for better visability.
=> Change shadow effect in the HeaderUserMenu and import in the ProductCard

src/components/CalendarBlock/CalendarBlock.jsx, src/components/MeetYourhostSection/MeetYourHostLeft/MeetYourHostLeft.module.css, src/components/MeetYourhostSection/MeetYourHostSection.module.css
This PR fixes responsive design in MeetYourHostSection along with Calendar
=> Fix responsive design in MeetYourHostSection along with Calendar
